# Generated by Django 3.1.2 on 2020-10-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RidayProducts11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('opens', models.CharField(blank=True, max_length=255, null=True)),
                ('closes', models.CharField(blank=True, max_length=255, null=True)),
                ('high', models.CharField(blank=True, max_length=255, null=True)),
                ('low', models.CharField(blank=True, max_length=255, null=True)),
                ('volume', models.CharField(blank=True, max_length=255, null=True)),
                ('volumemoney', models.CharField(blank=True, max_length=255, null=True)),
                ('huanshou', models.CharField(blank=True, max_length=255, null=True)),
                ('names', models.CharField(blank=True, max_length=255, null=True)),
                ('codes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'riday_products11',
                'managed': False,
            },
        ),
    ]
